import type { Metadata } from "next";
import Link from "next/link";
import { CarCard } from "@/components/car/CarCard";
import { cars } from "@/lib/mock-data";

export const metadata: Metadata = { title: "Véhicules d'occasion", description: "Découvrez les véhicules d'occasion disponibles chez Mecano." };
export const revalidate = 3600;
interface CarsPageProps { searchParams: Promise<{ marque?: string; prix_max?: string; inclure_vendus?: string }>; }
export default async function CarsPage({ searchParams }: CarsPageProps) {
  const filters = await searchParams;
  const filteredCars = cars.filter((car) => (!filters.marque || car.brand.toLowerCase() === filters.marque) && (!filters.prix_max || car.priceXaf <= Number(filters.prix_max)) && (filters.inclure_vendus === "1" || car.status !== "sold"));
  const brands = [...new Set(cars.map((car) => car.brand))];
  return <><section className="bg-slate-950 px-5 py-16 text-white"><div className="mx-auto max-w-7xl lg:px-8"><p className="text-sm font-bold uppercase tracking-[.2em] text-emerald-300">Le catalogue</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-6xl">Trouvez votre prochaine voiture.</h1><p className="mt-5 max-w-2xl text-lg text-slate-300">Chaque annonce présente un véhicule contrôlé, avec les informations utiles avant votre appel.</p></div></section><main className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><form className="grid gap-4 rounded-3xl border border-slate-200 bg-slate-50 p-5 md:grid-cols-[1fr_1fr_auto]"><label className="text-sm font-bold text-slate-700">Marque<select name="marque" defaultValue={filters.marque} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 font-normal"><option value="">Toutes les marques</option>{brands.map((brand) => <option key={brand} value={brand.toLowerCase()}>{brand}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Budget maximum<select name="prix_max" defaultValue={filters.prix_max} className="mt-2 w-full rounded-xl border border-slate-300 bg-white px-3 py-3 font-normal"><option value="">Tous les budgets</option><option value="8000000">8 000 000 FCFA</option><option value="12000000">12 000 000 FCFA</option><option value="15000000">15 000 000 FCFA</option></select></label><button className="self-end rounded-xl bg-emerald-700 px-6 py-3 font-bold text-white">Filtrer</button></form><div className="mt-10 flex items-center justify-between"><p className="text-sm font-semibold text-slate-500">{filteredCars.length} véhicule{filteredCars.length > 1 ? "s" : ""} disponible{filteredCars.length > 1 ? "s" : ""}</p><Link href="/voitures?inclure_vendus=1" className="text-sm font-bold text-emerald-700">Voir aussi les véhicules vendus</Link></div>{filteredCars.length ? <div className="mt-6 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{filteredCars.map((car) => <CarCard key={car.slug} car={car} />)}</div> : <section className="mt-8 rounded-3xl bg-emerald-50 p-10 text-center"><h2 className="text-2xl font-extrabold text-slate-950">Aucun véhicule pour ces critères.</h2><p className="mt-3 text-slate-600">Élargissez votre recherche ou échangez avec nous pour une recherche personnalisée.</p><Link href="/voitures" className="mt-6 inline-block font-bold text-emerald-700">Réinitialiser les filtres →</Link></section>}</main></>;
}
